version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Flyway..."
      - mkdir -p /opt/flyway
      - curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.13.0/flyway-commandline-10.13.0-linux-x64.tar.gz -o flyway.tar.gz
      - tar -xzf flyway.tar.gz -C /opt/flyway --strip-components=1
      - export PATH=$PATH:/opt/flyway
  pre_build:
    commands:
      - echo "📁 Listing files in working directory:"
      - pwd
      - ls -la
      - echo "🔄 Loading environment variables from .env..."
      - if [ -f .env ]; then source .env; else echo "❌ .env file not found!"; exit 1; fi
  build:
    commands:
      - echo "🚀 Running Flyway migrations from root directory..."
      - flyway -url=$FLYWAY_URL -user=$FLYWAY_USER -password=$FLYWAY_PASSWORD -locations=filesystem:. migrate

artifacts:
  files:
    - flyway.conf
    - flyway.log
    - flyway_output.txt
