version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Flyway..."
      - mkdir -p /opt/flyway
      - curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.13.0/flyway-commandline-10.13.0-linux-x64.tar.gz -o flyway.tar.gz
      - tar -xzf flyway.tar.gz -C /opt/flyway --strip-components=1
      - export PATH=$PATH:/opt/flyway
  pre_build:
    commands:
      - echo "Loading environment variables from .env..."
      - source .env
  build:
    commands:
      - echo "Running Flyway migrations from root directory..."
      - flyway -url=$FLYWAY_URL -user=$FLYWAY_USER -password=$FLYWAY_PASSWORD -locations=filesystem:. migrate
